# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------
[[module.imports]]
path = "github.com/Artexxx/cmpt-post-preview"

[hugoVersion]
extended = true
min = "0.147.7"
