# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------

[[imports]]
path = "github.com/hugo-fixit/FixIt"

[[imports]]
path = "github.com/hugo-fixit/shortcode-docs-bookmark"

[[imports]]
path = "github.com/hugo-fixit/hugo-atom-feed"

[[imports]]
path = "github.com/hugo-fixit/hugo-json-feed"

[[imports]]
path = "github.com/Artexxx/cmpt-post-preview"
[[module.mounts]]
source = "cmpt-post-preview/layouts"
target = "layouts"

[hugoVersion]
extended = true
min = "0.147.7"
