description = "This is my new Artexxx blog"
keywords = ["Hugo", "FixIt"]

[author]
name = "Artexxx"
email = "otboynik50@gmail.com"
link = "https://artexxx.github.io/"
avatar = "https://avatars.githubusercontent.com/u/54672403"

[app]
title = "Artexxx Blog"

[header]

[header.title]
logo = "/images/logo.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
