# -------------------------------------------------------------------------------------
# Modules Configuration
# See: https://gohugo.io/configuration/module/
# -------------------------------------------------------------------------------------


[[imports]]
path = "github.com/hugo-fixit/FixIt"

[[imports]]
path = "github.com/hugo-fixit/shortcode-docs-bookmark"

[[imports]]
path = "github.com/hugo-fixit/hugo-atom-feed"

[[imports]]
path = "github.com/hugo-fixit/hugo-json-feed"

[[imports]]
path = "github.com/hugo-fixit/shortcode-asciinema"

[[imports]]
path = "github.com/Artexxx/cmpt-post-preview"

[[imports]]
path = "github.com/Artexxx/cmpt-graph-view"

[[imports]]
path = "github.com/Artexxx/shortcode-jupyter-notebook"

[hugoVersion]
extended = true
min = "0.147.7"
