description = "This is my new Artexxx site"
keywords = ["Hugo", "FixIt"]

[author]
name = "Artexxx"
email = ""
link = "https://github.com/Artexxx"
avatar = "https://avatars.githubusercontent.com/u/54672403?v=4"

[app]
title = "Artexxx Blog"

[header]

[header.title]
logo = "/hugo-fixit-starter/images/fixit.min.svg"

[home]

[home.profile]
enable = true

[customPartials]
head = [
  "inject/fixit-docs-bookmark.html",
]
